spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/carb_db
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: YW55d2hlcmVyYWlzZXNhaWxiZXR3ZWVuYXZlcmFnZW1vcm5pbmdwYXNzYWdlc2hlZXQ=
  expiration: 86400000 #срок годности токена в миллисекундах